#!/usr/bin/env python3
"""Publish a successful build's media and binary link without replaying stale source.

Run in a disposable, clean CI checkout. Downloaded media may be in an untracked
directory in that checkout, or outside it. Every push is a normal fast-forward
push; a competing update causes a fresh source check and overlay on its new tip.
"""

import argparse
from pathlib import Path
import re
import subprocess
import sys


PEAKS_BEGIN = (
    b"<!-- peaks-table-begin: regenerated by ElectryRenderDemos;"
    b" edits between the markers are overwritten -->"
)
PEAKS_END = b"<!-- peaks-table-end -->"
DOWNLOAD_BEGIN = b"<!-- build-download-begin: updated by the Main build workflow -->"
DOWNLOAD_END = b"<!-- build-download-end -->"
ARTIFACT_URL = re.compile(
    r"https://github\.com/[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?/"
    r"[A-Za-z0-9_-][A-Za-z0-9_.-]*/actions/runs/[1-9][0-9]*/artifacts/[1-9][0-9]*"
)
PUBLISHED_BUILD = re.compile(
    rb"\*\*\[Download distributable binaries \xe2\x80\x94 build ([0-9]+)\]\("
)
SCREENSHOT = "Docs/screenshots/electry-standalone.png"
WAV_NAME = re.compile(r"(0[1-9]|1[0-9]|2[0-3])-[a-z0-9]+(?:-[a-z0-9]+)*\.wav")


def git(repo, *args, check=True):
    result = subprocess.run(
        ["git", *args], cwd=repo, capture_output=True, check=False
    )
    if check and result.returncode:
        # A remote URL may contain the workflow token. Do not echo commands or
        # Git's stderr, which can repeat that URL in authentication failures.
        raise RuntimeError(f"git {args[0]} failed (exit {result.returncode})")
    return result


def readme_parts(data, begin=PEAKS_BEGIN, end_marker=PEAKS_END, name="peaks-table"):
    if data.count(begin) != 1 or data.count(end_marker) != 1:
        raise ValueError(f"README must contain exactly one pair of {name} markers")
    start = data.index(begin) + len(begin)
    end = data.index(end_marker)
    if end < start:
        raise ValueError(f"README {name} markers are out of order")
    return data[:start], data[start:end], data[end:]


def download_parts(data):
    return readme_parts(data, DOWNLOAD_BEGIN, DOWNLOAD_END, "build-download")


def readme_source(data):
    prefix, _, suffix = readme_parts(data)
    data = prefix + suffix
    # Older callers and source revisions may predate the download block.
    if DOWNLOAD_BEGIN in data or DOWNLOAD_END in data:
        prefix, _, suffix = download_parts(data)
        data = prefix + suffix
    return data


def validate_download(build_number, artifact_url):
    if build_number is None and artifact_url is None:
        return None
    if build_number is None or artifact_url is None:
        raise ValueError("--build-number and --artifact-url must be provided together")
    if re.fullmatch(r"[0-9]+", str(build_number)) is None or int(build_number) <= 0:
        raise ValueError("--build-number must be a positive ASCII integer")
    if ARTIFACT_URL.fullmatch(artifact_url) is None:
        raise ValueError("--artifact-url must be an HTTPS GitHub Actions artifact URL")
    return int(build_number)


def read_payload(media_dir):
    audio_dir = media_dir / "Docs/audio"
    wavs = sorted(audio_dir.glob("*.wav"))
    numbers = set()
    payload = {}
    if len(wavs) != 23:
        raise ValueError(f"Expected 23 rendered root WAVs, found {len(wavs)}")
    for path in wavs:
        match = WAV_NAME.fullmatch(path.name)
        if match is None or match[1] in numbers:
            raise ValueError(f"Invalid or duplicate demo number: {path.name}")
        numbers.add(match[1])
        data = path.read_bytes()
        if not data:
            raise ValueError(f"Empty rendered WAV: {path.name}")
        payload[f"Docs/audio/{path.name}"] = data

    screenshot = (media_dir / SCREENSHOT).read_bytes()
    if not screenshot.startswith(b"\x89PNG\r\n\x1a\n") or not screenshot.endswith(
        b"IEND\xaeB`\x82"
    ):
        raise ValueError("Rendered screenshot has no complete PNG signature/trailer")
    payload[SCREENSHOT] = screenshot
    _, table, _ = readme_parts((media_dir / "README.md").read_bytes())
    if not table.strip():
        raise ValueError("Rendered README peaks table is empty")
    return payload, table


def root_wav(path):
    parts = path.split("/")
    return len(parts) == 3 and parts[:2] == ["Docs", "audio"] and path.endswith(".wav")


def source_is_current(repo, source, tip):
    ancestry = git(repo, "merge-base", "--is-ancestor", source, tip, check=False)
    if ancestry.returncode == 1:
        return False
    if ancestry.returncode:
        raise RuntimeError("Could not verify source ancestry; fetch the source history")
    changed = git(repo, "diff", "--name-only", "--no-renames", "-z", source, tip).stdout
    for path in changed.decode("utf-8", "surrogateescape").split("\0"):
        if not path or root_wav(path) or path == SCREENSHOT:
            continue
        if path != "README.md":
            return False
        before = readme_source(git(repo, "show", f"{source}:README.md").stdout)
        after = readme_source(git(repo, "show", f"{tip}:README.md").stdout)
        if before != after:
            return False
    return True


def apply_payload(repo, payload, table, build_number=None, artifact_url=None):
    # Only the canonical directory's root WAVs belong to the renderer. Frozen
    # listening evidence in subdirectories is never replaced or staged.
    audio_dir = repo / "Docs/audio"
    audio_dir.mkdir(parents=True, exist_ok=True)
    for path in audio_dir.glob("*.wav"):
        if f"Docs/audio/{path.name}" not in payload:
            path.unlink()
    for relative_path, data in payload.items():
        path = repo / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_symlink():
            path.unlink()
        path.write_bytes(data)
    readme_path = repo / "README.md"
    prefix, _, suffix = readme_parts(readme_path.read_bytes())
    readme = prefix + table + suffix
    if build_number is not None:
        prefix, _, suffix = download_parts(readme)
        download = (
            f"\n**[Download distributable binaries — build {build_number}]({artifact_url})**\n"
        ).encode("utf-8")
        readme = prefix + download + suffix
    readme_path.write_bytes(readme)
    git(
        repo, "add", "-A", "--", ":(glob)Docs/audio/*.wav", SCREENSHOT, "README.md"
    )


def refresh(source_commit, media_dir, remote, branch, build_number=None, artifact_url=None):
    build_number = validate_download(build_number, artifact_url)
    repo = Path(git(None, "rev-parse", "--show-toplevel").stdout.decode().strip())
    media_dir = media_dir.resolve(strict=True)
    payload, table = read_payload(media_dir)
    git(repo, "check-ref-format", f"refs/heads/{branch}")
    for args in (("diff", "--quiet"), ("diff", "--cached", "--quiet")):
        if git(repo, *args, check=False).returncode:
            raise ValueError("Generated media refresh requires a clean tracked checkout")
    try:
        relative_media = media_dir.relative_to(repo).as_posix()
    except ValueError:
        relative_media = None
    if relative_media is not None:
        tracked = git(repo, "ls-files", "-z").stdout.decode("utf-8", "surrogateescape")
        if relative_media == "." or any(
            path == relative_media or path.startswith(relative_media + "/")
            for path in tracked.split("\0") if path
        ):
            raise ValueError("Downloaded media directory must not contain tracked files")
    source = git(
        repo, "rev-parse", "--verify", "--end-of-options", f"{source_commit}^{{commit}}"
    ).stdout.decode().strip()
    if build_number is not None:
        download_parts(git(repo, "show", f"{source}:README.md").stdout)

    for _ in range(3):
        git(repo, "fetch", "--no-tags", "--", remote, f"refs/heads/{branch}")
        tip = git(repo, "rev-parse", "FETCH_HEAD").stdout.decode().strip()
        if build_number is not None:
            _, download, _ = download_parts(git(repo, "show", f"{tip}:README.md").stdout)
            published = PUBLISHED_BUILD.search(download)
            if published is not None and int(published[1]) > build_number:
                print("Skipped outdated build: README already links to a newer build.")
                return
        if not source_is_current(repo, source, tip):
            print("Skipped outdated generated media: main source changed during the build.")
            return
        git(repo, "switch", "--detach", tip)
        apply_payload(repo, payload, table, build_number, artifact_url)
        if git(repo, "diff", "--cached", "--quiet", check=False).returncode == 0:
            print("Generated media is unchanged; no commit needed.")
            return
        git(
            repo, "-c", "user.name=github-actions[bot]", "-c",
            "user.email=41898282+github-actions[bot]@users.noreply.github.com",
            "commit", "-m", f"CI: refresh generated media for {source[:12]}",
            "-m", f"Source commit: {source}",
        )
        pushed = git(repo, "push", "--", remote, f"HEAD:refs/heads/{branch}", check=False)
        if pushed.returncode == 0:
            print(f"Updated {branch} with generated media from {source}.")
            return
        print("Push did not succeed; fetching the branch again before retrying.")
    raise RuntimeError("Could not push generated media after three attempts")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-commit", required=True)
    parser.add_argument("--media-dir", type=Path, required=True)
    parser.add_argument("--remote", default="origin")
    parser.add_argument("--branch", default="main")
    parser.add_argument("--build-number")
    parser.add_argument("--artifact-url")
    args = parser.parse_args()
    try:
        refresh(args.source_commit, args.media_dir, args.remote, args.branch,
                args.build_number, args.artifact_url)
    except (OSError, ValueError, RuntimeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
